version: '3.8'

services:
  postgres:
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

  app:
    environment:
      SPRING_JPA_SHOW_SQL: 'true'
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: 'true'
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_COM_PROJECT_TASKIPRO: DEBUG
