version: '3.8'

services:
  postgres:
    image: postgres:15.2
    container_name: taskipro-postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: taskipro
      POSTGRES_USER: taskipro
      POSTGRES_PASSWORD: taskipro
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - taskipro-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskipro-app
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskipro
      SPRING_DATASOURCE_USERNAME: taskipro
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    networks:
      - taskipro-network

networks:
  taskipro-network:
    driver: bridge

volumes:
  postgres-data:
