version: '3.8'

services:
  postgres:
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: taskipro
      POSTGRES_USER: taskipro
      POSTGRES_PASSWORD: taskipro
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

  app:
    environment:
      SPRING_JPA_SHOW_SQL: 'true'
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: 'true'
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_COM_PROJECT_TASKIPRO: DEBUG
